### ISSUE TITLE
有哪几种常用的清除浮动方法？

### ISSUE THREAD

**Issue by artdong** [daily-interview/fe-interview#3]
有哪几种常用的清除浮动方法？

**Comment by FunnyZ** [comment]
- 父级元素添加伪元素
```css
.clear-float:after {
    content: '';
    display: block;
    clear: both;
}
```
- 在与浮动元素平级的最后面添加新元素 div.clear
```css
.clear {
    clear: both;
}
```
- 在父级元素添加样式 overflow: auto; 或者 overflow: hidden; 会存在兼容性问题。
